### PR TITLE
add architecture display

### PR DESCRIPTION
**Pull request by ofirgalcon**
Added architecture display and fixed the code for macos versions that return the architecture in arch_kind and not in runtime_environment

The version I have which came with the latest MR zip install seems slightly different to the one on github and I am not sure which version is the latest.

### CODE REVIEW

**Comment by bochoven** [comment]
Please resolve conflicts

**Comment by ofirgalcon** [comment]
Updated

**Comment by ofirgalcon** [comment]
Hi

I may have confused things with Git. Would it help if I upload a fresh copy of my version? https://github.com/munkireport/applications/compare/master...ofirgalcon:master shows the diff

**Comment by tuxudo** [comment]
Those changes are already merged into the repo. They were merged in with PR #8

**Pull request merged**
